#ifndef __CMAP_PARSER_OP_H__
#define __CMAP_PARSER_OP_H__

#include "cmap-parser-op-define.h"

CMAP_PARSER_OP_LOOP(CMAP_PARSER_OP_DECL)

CMAP_PARSER_OP_SELF_LOOP(CMAP_PARSER_OP_SELF_DECL)

CMAP_PARSER_OP_UNIQUE_LOOP(CMAP_PARSER_OP_UNIQUE_DECL)

#endif
