
#include "cmap-stack.h"

CMAP_STACK_IMPL(map, CMAP_MAP *)
CMAP_STACK_IMPL(lc, CMAP_LIFECYCLE *)
CMAP_STACK_IMPL(lc_ptr, CMAP_LIFECYCLE **)
CMAP_STACK_IMPL(proc_ctx, CMAP_PROC_CTX *)
CMAP_STACK_IMPL(char_ptr, char *)
